### ISSUE TITLE
Question: Which tool have you used for generating the log?

### ISSUE THREAD

**Issue by marandaneto** [mrqc/stopcorona-runtime-analysis#1]
cool stuff :)

**Comment by mrqc** [comment]
This is a tool developed by myself at blackxerus.com. Its called AndroidXMIner. Its a govTech/ReverseEngineering/Forensic tool I am going to bring to the market currently.

**Comment by marandaneto** [comment]
cool, let me know once it's done, thanks @mrqc

**Comment by mrqc** [comment]
My Software is now in a version 1.0.

**Comment by mrqc** [comment]
May I ask you, why would you need it?

**Comment by marandaneto** [comment]
@mrqc I'm a developer and I do often reverse engineering as well.
It'd be cool to compare with other tools that I've been using out there, that's the only reason.

**Comment by mrqc** [comment]
I tried to contact you but it did not work. How to reach you? Would be interesting....

**Comment by marandaneto** [comment]
@mrqc maybe via twitter DM? https://twitter.com/marandaneto
